purposely break test
gblock0/testGit pull request #2
Opened 2019-11-18 17:40 UTC by gblock0

2019-11-18 17:44 UTC, gblockpath commented on TestGit.Tests/Tests.cs
> +            Assert.AreEqual(firstArg, "test3");
I think this should be `test2`?
```suggestion
            Assert.AreEqual(firstArg, "test2");
```

2019-11-18 17:44 UTC, ghost requested changes
This needs to be fixed (also the test is broken)

2019-11-18 17:47 UTC, gblock0 commented on TestGit.Tests/Tests.cs
> -            Assert.AreEqual(firstArg, "test2");
This is good otherwise...

2019-11-18 18:53 UTC, gblock0 commented
This will fix TG-1

2019-11-18 19:37 UTC, gblock0 commented
^ That revert was made with 2 clicks in the Github Desktop UI :D

2019-11-21 01:21 UTC, gblock0 commented
TG-1 Test

2019-11-21 20:24 UTC, techgerm requested changes
Needs more work!

2019-11-21 20:24 UTC, germanp173 commented on TestGit/Program.cs
>              return args[0];
Something is up here!

2019-11-21 20:24 UTC, germanp173 commented on TestGit.Tests/Tests.cs
> +            var args = new[] {"test2", "test3", "test4"};
Maybe test 5?

2019-11-28 21:22 UTC, techgerm approved these changes

2020-06-09 19:15 UTC, closed without merging